const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

/**
 * auto-fix-pr
 * Tier 1 closed-loop remediation: opens a real GitHub Pull Request on the target
 * repository with a documentation patch describing the IntelliOps-recommended fix.
 *
 * This is intentionally conservative — it never modifies production source files.
 * Instead it creates / updates a file at `.intelliops/fixes/<timestamp>.md` containing
 * the finding + AI suggestion, opens a branch, and raises a PR for human review.
 * That gives a genuine, auditable closed loop without the risk of breaking builds.
 */

interface RequestBody {
  repo: string; // owner/name
  finding: string;
  fixSuggestion: string;
  decision: string;
  confidence?: number;
}

const GITHUB_API = "https://api.github.com";

async function logDecision(row: Record<string, unknown>) {
  const url = Deno.env.get("SUPABASE_URL");
  const key = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  if (!url || !key) return;
  try {
    await fetch(`${url}/rest/v1/decisions`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        apikey: key,
        Authorization: `Bearer ${key}`,
        Prefer: "return=minimal",
      },
      body: JSON.stringify(row),
    });
  } catch (e) {
    console.error("logDecision failed:", e);
  }
}

async function gh(path: string, token: string, init: RequestInit = {}) {
  const res = await fetch(`${GITHUB_API}${path}`, {
    ...init,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
      "Content-Type": "application/json",
      "User-Agent": "intelliops-auto-fix",
      ...(init.headers || {}),
    },
  });
  const text = await res.text();
  let data: any = null;
  try { data = text ? JSON.parse(text) : null; } catch { data = text; }
  if (!res.ok) {
    throw new Error(`GitHub ${res.status}: ${typeof data === "string" ? data : JSON.stringify(data)}`);
  }
  return data;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  try {
    const token = Deno.env.get("GITHUB_ACCESS_TOKEN");
    if (!token) throw new Error("GITHUB_ACCESS_TOKEN not configured");

    const body = (await req.json()) as RequestBody;
    if (!body?.repo || !body?.finding) throw new Error("repo and finding are required");
    if (!body.repo.includes("/")) throw new Error("repo must be in 'owner/name' format");

    // Basic input validation to prevent abuse / oversized payloads
    if (body.repo.length > 140 || !/^[\w.-]+\/[\w.-]+$/.test(body.repo)) {
      throw new Error("invalid repo format");
    }
    if (body.finding.length > 4000) throw new Error("finding too long");
    if (body.fixSuggestion && body.fixSuggestion.length > 8000) throw new Error("fixSuggestion too long");
    if (body.decision && body.decision.length > 60) throw new Error("decision too long");

    const [owner, repoName] = body.repo.split("/");

    // 1. Get repo metadata (default branch + ensure access)
    const repoMeta = await gh(`/repos/${owner}/${repoName}`, token);
    const defaultBranch: string = repoMeta.default_branch;

    // 2. Get HEAD sha of default branch
    const ref = await gh(`/repos/${owner}/${repoName}/git/ref/heads/${defaultBranch}`, token);
    const baseSha: string = ref.object.sha;

    // 3. Create new branch
    const ts = Date.now();
    const branch = `intelliops/auto-fix-${ts}`;
    await gh(`/repos/${owner}/${repoName}/git/refs`, token, {
      method: "POST",
      body: JSON.stringify({ ref: `refs/heads/${branch}`, sha: baseSha }),
    });

    // 4. Create the fix documentation file
    const fixPath = `.intelliops/fixes/${ts}.md`;
    const fileContent = [
      `# IntelliOps Auto-Fix Recommendation`,
      ``,
      `**Generated:** ${new Date().toISOString()}`,
      `**Decision:** ${body.decision}`,
      `**Confidence:** ${body.confidence ?? "n/a"}%`,
      ``,
      `## Finding`,
      ``,
      body.finding,
      ``,
      `## Recommended Fix`,
      ``,
      body.fixSuggestion || "(no suggestion provided)",
      ``,
      `---`,
      `_Generated by the IntelliOps Jidoka Decision Engine (Layer 4 closed-loop remediation)._`,
    ].join("\n");

    const contentB64 = btoa(unescape(encodeURIComponent(fileContent)));

    await gh(`/repos/${owner}/${repoName}/contents/${fixPath}`, token, {
      method: "PUT",
      body: JSON.stringify({
        message: `chore(intelliops): auto-fix recommendation for finding`,
        content: contentB64,
        branch,
      }),
    });

    // 5. Open the PR
    const pr = await gh(`/repos/${owner}/${repoName}/pulls`, token, {
      method: "POST",
      body: JSON.stringify({
        title: `[IntelliOps] Auto-fix: ${body.finding.slice(0, 60)}`,
        head: branch,
        base: defaultBranch,
        body: `## 🤖 IntelliOps Auto-Fix\n\n**Finding:** ${body.finding}\n\n**Suggested fix:** ${body.fixSuggestion}\n\n**Decision:** \`${body.decision}\` · **Confidence:** ${body.confidence ?? "n/a"}%\n\nThis PR was opened automatically by the IntelliOps Jidoka Decision Engine. Review the recommendation in \`${fixPath}\` and apply the underlying code change.`,
      }),
    });

    await logDecision({
      repository: body.repo,
      finding: body.finding,
      decision: body.decision ?? "unknown",
      confidence: body.confidence ?? null,
      fix_suggestion: body.fixSuggestion ?? null,
      pr_url: pr.html_url,
      pr_number: pr.number,
      branch_name: branch,
      execution_status: "pr_created",
    });

    return new Response(
      JSON.stringify({
        success: true,
        prUrl: pr.html_url,
        prNumber: pr.number,
        branch,
      }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" }, status: 200 },
    );
  } catch (e: any) {
    console.error("auto-fix-pr error:", e);
    try {
      const b = await req.clone().json().catch(() => null) as RequestBody | null;
      if (b?.repo && b?.finding) {
        await logDecision({
          repository: b.repo,
          finding: b.finding,
          decision: b.decision ?? "unknown",
          confidence: b.confidence ?? null,
          fix_suggestion: b.fixSuggestion ?? null,
          execution_status: "failed",
          error_message: String(e?.message ?? e).slice(0, 500),
        });
      }
    } catch (_) {}
    return new Response(
      JSON.stringify({ success: false, error: e?.message ?? String(e) }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" }, status: 500 },
    );
  }
});