import { corsHeaders } from "@supabase/supabase-js/cors";

/**
 * auto-fix-pr
 * Tier 1 closed-loop remediation: opens a real GitHub Pull Request on the target
 * repository with a documentation patch describing the IntelliOps-recommended fix.
 *
 * This is intentionally conservative — it never modifies production source files.
 * Instead it creates / updates a file at `.intelliops/fixes/<timestamp>.md` containing
 * the finding + AI suggestion, opens a branch, and raises a PR for human review.
 * That gives a genuine, auditable closed loop without the risk of breaking builds.
 */

interface RequestBody {
  repo: string; // owner/name
  finding: string;
  fixSuggestion: string;
  decision: string;
  confidence?: number;
}

const GITHUB_API = "https://api.github.com";

async function gh(path: string, token: string, init: RequestInit = {}) {
  const res = await fetch(`${GITHUB_API}${path}`, {
    ...init,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
      "Content-Type": "application/json",
      "User-Agent": "intelliops-auto-fix",
      ...(init.headers || {}),
    },
  });
  const text = await res.text();
  let data: any = null;
  try { data = text ? JSON.parse(text) : null; } catch { data = text; }
  if (!res.ok) {
    throw new Error(`GitHub ${res.status}: ${typeof data === "string" ? data : JSON.stringify(data)}`);
  }
  return data;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  try {
    const token = Deno.env.get("GITHUB_ACCESS_TOKEN");
    if (!token) throw new Error("GITHUB_ACCESS_TOKEN not configured");

    const body = (await req.json()) as RequestBody;
    if (!body?.repo || !body?.finding) throw new Error("repo and finding are required");
    if (!body.repo.includes("/")) throw new Error("repo must be in 'owner/name' format");

    const [owner, repoName] = body.repo.split("/");

    // 1. Get repo metadata (default branch + ensure access)
    const repoMeta = await gh(`/repos/${owner}/${repoName}`, token);
    const defaultBranch: string = repoMeta.default_branch;

    // 2. Get HEAD sha of default branch
    const ref = await gh(`/repos/${owner}/${repoName}/git/ref/heads/${defaultBranch}`, token);
    const baseSha: string = ref.object.sha;

    // 3. Create new branch
    const ts = Date.now();
    const branch = `intelliops/auto-fix-${ts}`;
    await gh(`/repos/${owner}/${repoName}/git/refs`, token, {
      method: "POST",
      body: JSON.stringify({ ref: `refs/heads/${branch}`, sha: baseSha }),
    });

    // 4. Create the fix documentation file
    const fixPath = `.intelliops/fixes/${ts}.md`;
    const fileContent = [
      `# IntelliOps Auto-Fix Recommendation`,
      ``,
      `**Generated:** ${new Date().toISOString()}`,
      `**Decision:** ${body.decision}`,
      `**Confidence:** ${body.confidence ?? "n/a"}%`,
      ``,
      `## Finding`,
      ``,
      body.finding,
      ``,
      `## Recommended Fix`,
      ``,
      body.fixSuggestion || "(no suggestion provided)",
      ``,
      `---`,
      `_Generated by the IntelliOps Jidoka Decision Engine (Layer 4 closed-loop remediation)._`,
    ].join("\n");

    const contentB64 = btoa(unescape(encodeURIComponent(fileContent)));

    await gh(`/repos/${owner}/${repoName}/contents/${fixPath}`, token, {
      method: "PUT",
      body: JSON.stringify({
        message: `chore(intelliops): auto-fix recommendation for finding`,
        content: contentB64,
        branch,
      }),
    });

    // 5. Open the PR
    const pr = await gh(`/repos/${owner}/${repoName}/pulls`, token, {
      method: "POST",
      body: JSON.stringify({
        title: `[IntelliOps] Auto-fix: ${body.finding.slice(0, 60)}`,
        head: branch,
        base: defaultBranch,
        body: `## 🤖 IntelliOps Auto-Fix\n\n**Finding:** ${body.finding}\n\n**Suggested fix:** ${body.fixSuggestion}\n\n**Decision:** \`${body.decision}\` · **Confidence:** ${body.confidence ?? "n/a"}%\n\nThis PR was opened automatically by the IntelliOps Jidoka Decision Engine. Review the recommendation in \`${fixPath}\` and apply the underlying code change.`,
      }),
    });

    return new Response(
      JSON.stringify({
        success: true,
        prUrl: pr.html_url,
        prNumber: pr.number,
        branch,
      }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" }, status: 200 },
    );
  } catch (e: any) {
    console.error("auto-fix-pr error:", e);
    return new Response(
      JSON.stringify({ success: false, error: e?.message ?? String(e) }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" }, status: 500 },
    );
  }
});